# List of rules with definitions
# https://github.com/realm/SwiftLint/blob/master/Rules.md

# Find all the available rules by running:
# 1. With terminal navigate to project folder
# 2. Write: swiftlint rules

# rule identifiers to exclude from running
disabled_rules: 
#  - todo
#  - function_body_length
#  - closure_parameter_position
#  - attributes
#  - line_length
#  - conditional_returns_on_newline

opt_in_rules:
 - closure_spacing
 - conditional_returns_on_newline
 - empty_count
 - explicit_init
 - force_unwrapping
 - nimble_operator
 - operator_usage_whitespace
 - overridden_super_call
 - private_outlet
 - prohibited_super_call
 - redundant_nil_coalescing
 - switch_case_on_newline
 - closure_end_indentation
 - multiline_parameters
 - vertical_parameter_alignment_on_call
 - discouraged_object_literal

# rules with additional configuration
#line_length:
# warning: 160
# error: 170
# ignores_comments: true

function_parameter_count:
 warning: 5
 error: 7

type_name:
 min_length: 2
 max_length: 60

identifier_name:
 min_length: 2
 max_length: 60

custom_rules:
  numbers_smell:
    regex: '(return |case |\w\(|: |\?\? |\, |== |<=? |>=? |\+= |\-= |\/= |\*= |%= |\w\.\w+ = )\(*-?\d{2,}'
    message: "Magic numbers?!; Please define a constant instead."

  already_true:
    regex: "== true"
    message: "Don't compare to true, just use the bool value."

  already_bool:
    regex: "== false"
    message: "Don't compare to false, just use !value."

# optional rule (uncomment if you want to use it)
# file_length:
# warning: 750
# error: 1000
# ignore_comment_only_lines: true

type_body_length:
 warning: 400
 error: 450

cyclomatic_complexity:
 ignores_case_statements: true

private_outlet:
 allow_private_set: true

trailing_whitespace: 
 ignores_empty_lines: true
 ignores_comments: true

excluded:
- Pods
- NewsAppKarSpv/Resources/R.generated.swift
- "**/*/_*.swift"
- "**/*/*.generated.swift"
- "_*.swift"
- "*.generated.swift"

warning_threshold: 500

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
